name: Deploy Analyzer

on:
  push:
    branches:
      - master
    paths:
      - 'analyzer/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: |
          cd analyzer
          npm ci
      - name: Build
        run: |
          cd analyzer
          npm run build
      - name: Deploy
        run: |
          cd analyzer
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}